import { MemberProfile } from '@/constants/images';

function baseHinduBiodata(
  member: MemberProfile,
  overrides: Record<string, string> = {},
): Record<string, string> {
  const [communityShort] = member.community.split(',');
  const ageMatch = member.age.match(/(\d+)/);
  const birthYear = ageMatch ? String(new Date().getFullYear() - Number(ageMatch[1])) : '1995';

  return {
    registrationCommunity: 'hindu',
    religion: 'hindu',
    registrationNumber: `AM${member.id.padStart(6, '0')}`,
    fullName: member.name,
    education: 'btech',
    dateOfBirth: `15-05-${birthYear}`,
    birthTiming: 'morning',
    natchathiram: 'rohini',
    rasi: 'rishabam',
    lagnam: 'kanni',
    occupationType: 'private',
    occupation: 'professional',
    occupationDesignation: member.name.includes('Vignesh')
      ? 'Banking Professional'
      : 'Software Professional',
    monthlyIncome: '1l-2l',
    propertyDetails: 'own-house',
    propertyHouseType: 'individual',
    propertyHouseCount: '1',
    fatherName: 'Raman Iyer',
    motherName: 'Lakshmi Devi',
    irupidam: member.location.split(',')[0]?.trim() ?? member.location,
    totalFamilyMembers: '5',
    birthOrder: '2',
    marriedBrother: '0',
    marriedYoungerBrother: '0',
    marriedSister: '1',
    marriedYoungerSister: '0',
    unmarriedBrother: '1',
    unmarriedYoungerBrother: '0',
    unmarriedSister: '0',
    unmarriedYoungerSister: '1',
    complexion: 'wheatish',
    height: '173',
    seervarisai: 'as-per-custom',
    dasaBalance: 'balance',
    dasaYear: '2',
    dasaMonth: '4',
    dasaDay: '10',
    caste: communityShort?.trim() ?? member.community,
    nativePlace: member.location,
    ...overrides,
  };
}

const MOCK_MEMBER_BIODATA: Record<string, Record<string, string>> = {
  '1': baseHinduBiodata(
    {
      id: '1',
      name: 'Raghavan Iyer',
      age: '32 Years, 5\'11"',
      community: 'Iyer, Brahacharanam',
      location: 'Chennai, Tamil Nadu',
      image: '',
      gender: 'male',
      phoneNumber: '9876543210',
      interestStatus: 'sent',
    },
    { education: 'me', occupationDesignation: 'Chartered Accountant' },
  ),
  '2': baseHinduBiodata(
    {
      id: '2',
      name: 'Sanjay Kumar',
      age: '29 Years, 5\'9"',
      community: 'Pillai, Saiva Pillai',
      location: 'Madurai, Tamil Nadu',
      image: '',
      gender: 'male',
      phoneNumber: '9123456789',
      interestStatus: 'mutual',
    },
    { complexion: 'fair', height: '175' },
  ),
  '3': baseHinduBiodata(
    {
      id: '3',
      name: 'Vignesh Mani',
      age: '30 Years, 5\'8"',
      community: 'Vanniyar, Kula',
      location: 'Coimbatore, Tamil Nadu',
      image: '',
      gender: 'male',
      phoneNumber: '9988776655',
      interestStatus: 'received',
    },
    { occupationDesignation: 'Banking Professional', monthlyIncome: '1l-2l' },
  ),
  '4': {
    registrationCommunity: 'rc-christian',
    religion: 'christian',
    registrationNumber: 'AM000004',
    fullName: 'Priya Lakshmi',
    education: 'bcom',
    dateOfBirth: '20-08-1998',
    birthTiming: 'evening',
    occupationType: 'private',
    occupation: 'professional',
    occupationDesignation: 'Chartered Accountant',
    monthlyIncome: '8l-12l',
    propertyDetails: 'own-house',
    fatherName: 'David Raj',
    motherName: 'Mary Raj',
    irupidam: 'Chennai',
    totalFamilyMembers: '4',
    birthOrder: '1',
    marriedBrother: '0',
    marriedYoungerBrother: '0',
    marriedSister: '0',
    marriedYoungerSister: '0',
    unmarriedBrother: '1',
    unmarriedYoungerBrother: '0',
    unmarriedSister: '0',
    unmarriedYoungerSister: '0',
    complexion: 'wheatish',
    height: '160',
    seervarisai: 'no',
    expectations: 'God-fearing, educated partner from a good family.',
    nativePlace: 'Chennai, Tamil Nadu',
  },
  '5': baseHinduBiodata(
    {
      id: '5',
      name: 'Meera Devi',
      age: '25 Years, 5\'3"',
      community: 'Vanniyar, Kula',
      location: 'Madurai, Tamil Nadu',
      image: '',
      gender: 'female',
      phoneNumber: '9000054321',
      interestStatus: 'sent',
    },
    { education: 'bsc', height: '160', complexion: 'fair' },
  ),
  '6': baseHinduBiodata(
    {
      id: '6',
      name: 'Anitha Raj',
      age: '28 Years, 5\'5"',
      community: 'Pillai, Saiva Pillai',
      location: 'Coimbatore, Tamil Nadu',
      image: '',
      gender: 'female',
      phoneNumber: '9000098765',
      interestStatus: 'mutual',
    },
    { education: 'mba', occupationDesignation: 'Bank Manager' },
  ),
  '7': {
    registrationCommunity: 'csi-christian',
    religion: 'christian',
    registrationNumber: 'AM000007',
    fullName: 'Grace Thomas',
    education: 'bcom',
    dateOfBirth: '12-03-1999',
    birthTiming: 'morning',
    occupationType: 'private',
    occupation: 'professional',
    occupationDesignation: 'School Teacher',
    monthlyIncome: '50k-1l',
    propertyDetails: 'own-house',
    fatherName: 'Thomas Raj',
    motherName: 'Mary Thomas',
    irupidam: 'Tirunelveli',
    totalFamilyMembers: '4',
    birthOrder: '2',
    marriedBrother: '0',
    marriedYoungerBrother: '0',
    marriedSister: '0',
    marriedYoungerSister: '0',
    unmarriedBrother: '1',
    unmarriedYoungerBrother: '0',
    unmarriedSister: '0',
    unmarriedYoungerSister: '1',
    complexion: 'wheatish',
    height: '162',
    seervarisai: 'no',
    expectations: 'Faith-centred partner from a CSI Christian family.',
    nativePlace: 'Tirunelveli, Tamil Nadu',
  },
};

export function getMockMemberBiodata(memberId: string): Record<string, string> | undefined {
  return MOCK_MEMBER_BIODATA[memberId];
}
